### ISSUE TITLE
sets are shared between characters

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [DJSchaffner/BetterBags_ItemRack#3]
There is too much clutter in the set list, in this character all the sets from the others are present and empty
see attached image
![Screenshot_20240320_012631](https://github.com/DJSchaffner/BetterBags_ItemRack/assets/10689739/530a961d-6086-4309-85df-d936eade0823)

**Comment by DJSchaffner** [comment]
It is intentional that sets which don't belong to the current character are empty because I did not see a benefit of categorizing items from a different character in the bag and this would just lead to "over-categorizing" items.

As of right now, there is no possibility to remove those unused categories so while waiting for that feature (or features that enable a different solution) all category names are being stored to keep track of what was created by the addon and categories which are currently not needed, will be cleared.

The author of BetterBags told me he is planning on adding a way to create temporary categories which only last for the current login-session. This would also be a way to remove the clutter, but we have to wait.

Unfortunately, the more dynamic `RegisterCategoryFunction` approach does not work either, because for optimization reasons the results here are cached by BetterBags, which means it would not recategorize an item when it is added or removed from an ItemRack set.

**Comment by DJSchaffner** [comment]
I just went through the source of BetterBags and found a method for removing a custom category. Will experiment with it and see if it's safe to use. If so, I can remove unused categories but will probably migrate to the "temporary category" solution once it is available.

**Comment by DJSchaffner** [comment]
Turns out this is actually pretty doable right now. I just implemented it and will give it a bit of testing before releasing the new version

**Comment by DJSchaffner** [comment]
Changes appear to be stable. I am pushing a release now.
